In [1]:
import numpy as np

# Bir boyutlu array oluşturulur
bir_boyutlu = np.array([1, 2, 3, 4, 5], dtype=int)
print("Bir boyutlu array: ", bir_boyutlu)
print("Boyut: ", bir_boyutlu.ndim)
print("Eleman sayısı: ", bir_boyutlu.size)

Bir boyutlu array:  [1 2 3 4 5]
Boyut:  1
Eleman sayısı:  5


In [2]:
# İki boyutlu array oluşturulur
iki_boyutlu = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print("\nİki boyutlu array: \n", iki_boyutlu)
print("Boyut: ", iki_boyutlu.ndim)
print("Eleman sayısı: ", iki_boyutlu.size)
print("Satır, sütun: ", iki_boyutlu.shape)

# Üç boyutlu array oluşturulur
uc_boyutlu = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=int)
print("\nÜç boyutlu array: \n", uc_boyutlu)
print("Boyut: ", uc_boyutlu.ndim)
print("Eleman sayısı: ", uc_boyutlu.size)
print("Satır, sütun: ", uc_boyutlu.shape)


İki boyutlu array: 
 [[1 2 3]
 [4 5 6]]
Boyut:  2
Eleman sayısı:  6
Satır, sütun:  (2, 3)

Üç boyutlu array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Boyut:  3
Eleman sayısı:  12
Satır, sütun:  (2, 2, 3)


In [3]:
# Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi
print("\nİki boyutlu arrayin ilk satırı: ", iki_boyutlu[0])
print("Üç boyutlu arrayin ilk elemanı: ", uc_boyutlu[0, 0, 0])

# Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur
sifirlar = np.zeros((2, 3))
birler = np.ones((2, 3))


İki boyutlu arrayin ilk satırı:  [1 2 3]
Üç boyutlu arrayin ilk elemanı:  1


In [4]:
# Arrayler satır ve sütun bazında birleştirilir
birlestirilmis_satir = np.concatenate((sifirlar, birler), axis=0)
birlestirilmis_sutun = np.concatenate((sifirlar, birler), axis=1)

print("\nSatır bazında birleştirilmiş array: \n", birlestirilmis_satir)
print("Sütun bazında birleştirilmiş array: \n", birlestirilmis_sutun)


Satır bazında birleştirilmiş array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
Sütun bazında birleştirilmiş array: 
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
